source "https://rubygems.org"

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
